### ISSUE TITLE
FRONTEND:  Overall page structure (using components from other issues) 

### ISSUE THREAD

**Issue by rick02840** [NERDngo/nerdsummit2020#13]
Work on overall page structure -- leave placeholders for other components (billboards, sessions, etc.) for now.  
See design:  https://projects.invisionapp.com/share/JYUJKYU2SPE#/screens/390379823
UPDATE:
Link to design https://projects.invisionapp.com/share/SYV4JDAMBGD#/screens
Link to notes from the designers:  https://docs.google.com/document/d/1DoMkoVf_sYEi_-ODmMqnsxWrnfm0_AX8uFIL01e9rJ0/edit

**Comment by starshaped** [comment]
I created a pull request as a starting point for the new site. There isn't any styling yet, but I stripped down a lot of the HTML and based it off of the designs above. Take a look!

https://github.com/NERDngo/nerdsummit2020/pull/15

**Comment by rick02840** [comment]
Some adjustments need to be made so that there is a max-width of 1200px on the content.  Now  there is no max width and margins on sections are %.  So maybe <main> needs a max width and adjust margins on <section>  appropriately.  

![NERDS_2019-12-09](https://user-images.githubusercontent.com/882512/70450933-8c42bf80-1a72-11ea-988b-a0e6ca31211a.jpg)
